MoveMapGen.exe 13 --silent --quick
MoveMapGen.exe 25 --silent --quick
MoveMapGen.exe 29 --silent --quick
MoveMapGen.exe 30 --silent --quick
MoveMapGen.exe 33 --silent --quick
MoveMapGen.exe 34 --silent --quick
MoveMapGen.exe 35 --silent --quick
MoveMapGen.exe 36 --silent --quick
MoveMapGen.exe 37 --silent --quick
MoveMapGen.exe 42 --silent --quick
MoveMapGen.exe 43 --silent --quick
MoveMapGen.exe 44 --silent --quick
MoveMapGen.exe 47 --silent --quick
MoveMapGen.exe 48 --silent --quick
MoveMapGen.exe 70 --silent --quick
MoveMapGen.exe 90 --silent --quick
MoveMapGen.exe 109 --silent --quick
MoveMapGen.exe 129 --silent --quick
MoveMapGen.exe 169 --silent --quick
MoveMapGen.exe 189 --silent --quick
MoveMapGen.exe 209 --silent --quick
