MoveMapGen.exe 229 --silent --quick
MoveMapGen.exe 230 --silent --quick
MoveMapGen.exe 249 --silent --quick
MoveMapGen.exe 269 --silent --quick
MoveMapGen.exe 289 --silent --quick
MoveMapGen.exe 309 --silent --quick
MoveMapGen.exe 329 --silent --quick
MoveMapGen.exe 349 --silent --quick
MoveMapGen.exe 369 --silent --quick
MoveMapGen.exe 389 --silent --quick
MoveMapGen.exe 409 --silent --quick
MoveMapGen.exe 429 --silent --quick
MoveMapGen.exe 449 --silent --quick
MoveMapGen.exe 450 --silent --quick
MoveMapGen.exe 451 --silent --quick
MoveMapGen.exe 469 --silent --quick
MoveMapGen.exe 489 --silent --quick
MoveMapGen.exe 509 --silent --quick
MoveMapGen.exe 529 --silent --quick
MoveMapGen.exe 531 --silent --quick
MoveMapGen.exe 533 --silent --quick